import pandas as pd

df=pd.read_csv("List of Orders.csv")
print(df.columns)
print(df.dtypes)
print(df.shape)
print("after cleaning and modifying")
df=df.dropna(how="all")
df = df.reset_index(drop=True)
df['Order Date']=pd.to_datetime(df['Order Date'],errors='coerce')
print(df.shape)
print(df.dtypes)
print(df.shape[0])
print(df.shape[1])
print(df.head())
print("the total orders:",len(df['Order ID']))

df=pd.read_csv("Order Details.csv")
print(df.columns)
print(df.dtypes)
print(df.shape)
print("after cleaning and modifying")
df=df.dropna(how="all")
df = df.reset_index(drop=True)
print(df.shape)
df['Amount'] = df['Amount'].astype(int)
df['Profit'] = df['Profit'].astype(int)
df['Profit'] = pd.to_numeric(df['Profit'], errors='coerce')
df['Amount'] = pd.to_numeric(df['Amount'],errors='coerce')
print(df.dtypes)
print(df.head())
print("\nthe total profit:",df['Profit'].sum())

df=pd.read_csv("Sales target.csv")
print(df.columns)
print(df.dtypes)
print(df.shape)
print("after cleaning and modifying")
df=df.dropna(how="all")
df = df.reset_index(drop=True)
print(df.shape)
df['Target'] = df['Target'].astype(int)
print(df.dtypes)
print(df.head())
print("the total target value:",df['Target'].sum())
